### ISSUE TITLE
[docs] Adds a description of all tables & general workflow

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#216]
Similar to UML of tables, there is no clear description of table logics for non-expert users.

We should document this

What we need:
- [x] Table description & logic (#227)
- [x] Event lifecycle (#227)
- [x] Table UML diagram (#228)
- [x] #168
- [x] External services (storage, DB) (#227)
- [x] #221
- [x] #225
- [x] #230

**Comment by fe51** [comment]
Thank for opening this, 

What description do you think is needed here ? 

- [ ] An entity diagram of tables
- [ ] A file describing tables and its fields ?  Do you have an idea of the relevant format ?
