### ISSUE TITLE
[storage] Add an option to have the storage as a local container

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#217]
To get the full process to work, there is no way currently to get around the storage solution.
We should have a local docker alternative to have everything offline

I suggest the following steps:
- [x] Standardize storage to S3-interfaced buckets (#220)
- [x] Adds a local container as S3 storage (#244)
- [x] Incorporate that so that the CI is running all bucket interactions during unittests (#244)

**Comment by frgfm** [comment]
LocalStack might be a good option:
- repo : https://github.com/localstack/localstack
- aws-cli wrapper: https://github.com/localstack/awscli-local
- tuto : https://nikhilvijayan.com/aws-s3-create-bucket-copy-files-localstack

**Comment by fe51** [comment]
Hi there, thanks for open the issue ! 

I have briefly experienced localstack in my previous experience (in an AWS stack context) and that could fit our need in replicating storage process ! 

How do you see the implementation ? 
- having a specific docker compose (with local stack) for local dev ? 
- whatever the solution adopted, a nice documentation to guide our dev is needed :)

**Comment by frgfm** [comment]
Sorry I thought I had replied!

> having a specific docker compose (with local stack) for local dev ?

yes, that exactly (having all services being able to be run locally or outsourced to the cloud so that everything can be tested reliably)

> a nice documentation to guide our dev is needed :)

Of course, the contributing file will be significantly extended haha
